### ISSUE TITLE
[3장] 자바스크립트 개발 환경과 실행 방법

### ISSUE THREAD

**Issue by yuiseo** [Pioneers-FE/DevBookshelf#1]
아래 템플릿을 복사해서 1개이상 퀴즈를 만들어주세요. 객관식, 주관식, 단답형 모두 상관없습니다!

Q. 퀴즈 내용
1.  1번
2.  2번
3.  3번

```
<details>
<summary>퀴즈 정답</summary>
<div markdown="1">    
정답 설명
</div>
</details>
```

**Comment by yuiseo** [comment]
Q. 다음 중 브라우저 환경에서 사용할 수 없는 기능은 무엇일까요?

1번 DOM 조작
2번 파일 생성 및 수정
3번 Client-side Web API (fetch, XMLHttpRequest)
4번 HTML 요소의 파싱

<details> <summary>퀴즈 정답</summary> <div markdown="1"> 정답: 2번 파일 생성 및 수정 브라우저 환경에서는 보안상의 이유로 파일 시스템 접근을 제한하여, 자바스크립트로 파일을 생성하거나 수정할 수 없습니다. </div> </details>

**Comment by yuiseo** [comment]
Q. 브라우저 환경에서 자바스크립트가 파일 시스템에 접근하지 못하도록 제한하는 주요 이유는 무엇인가요?

1번 자바스크립트의 용도가 제한적이기 때문에
2번 네트워크 속도를 높이기 위해
3번 브라우저가 파일 시스템 조작이 필요 없어서
4번 악성 코드로부터 사용자 컴퓨터를 보호하기 위해

<details> <summary>퀴즈 정답</summary> <div markdown="1"> 정답: 4번 악성 코드로부터 사용자 컴퓨터를 보호하기 위해 브라우저에서 자바스크립트가 파일 시스템에 접근하도록 허용하면 악성 코드가 로컬 파일을 삭제, 수정, 생성할 수 있는 위험이 발생하기 때문에 보안을 위해 제한합니다. </div> </details>

**Comment by ilmerry** [comment]
<blockquote>
❓ 퀴즈1

다음은 Node.js 환경에서 작성된 코드입니다.

```js
const arr = [1, 2, 3];

arr.forEach(alert);
```

위 코드를 실행하면 `ReferenceError: alert is not defined` 에러가 발생합니다. 해당 에러가 왜 발생하며, 에러를 해결하기 위해서는 어떻게 해야할까요?

<details>
<summary>정답</summary>

- 원인: alert 함수는 브라우저 환경에서만 동작하는 클라이언트 사이드 Web API이기 때문이다.(모자딥 p.32)

- 해결: npm을 통해 Web API를 실행할 수 있는 패키지를 다운로드한다.

</details>
</blockquote>

<br/>

<blockquote>
❓ 퀴즈2

```js
const fs = require('fs');

console.log(fs.readFileSync(txt파일, 'utf8');)
```

위 코드는 브라우저 환경에서 동작하지 않습니다. 그 이유를 작성하고, 올바르게 동작하도록 코드를 고쳐주세요.

<details>
<summary>정답</summary>

- 원인: 브라우저는 보안상의 이유로 파일 시스템을 제공하지 않는다.(모자딥 p.18)

- 해결: Web API인 FileReader 객체를 사용해 사용자가 지정한 파일 읽어들인다.

```js
const reader = new FileReader();

console.log(reader.readAsText(txt파일, 'utf8');)
```

</details>
</blockquote>
