### ISSUE TITLE
[7장] 연산자

### ISSUE THREAD

**Issue by yuiseo** [Pioneers-FE/DevBookshelf#10]
아래 템플릿을 복사해서 2개이상 퀴즈를 만들어주세요. 객관식, 주관식, 단답형 모두 상관없습니다!

```
Q. 퀴즈 내용
1.  1번
2.  2번
3.  3번

<details>
<summary>퀴즈 정답</summary>
<div markdown="1">    
정답 설명
</div>
</details>
```

**Comment by yuiseo** [comment]
Q1. ==와 ===의 차이점은 무엇인가요?
<details> <summary>퀴즈 정답</summary> <div markdown="1">
정답: ==는 값만 비교하는 느슨한 동등 비교로, 타입 변환을 통해 비교하고, ===는 값과 타입을 모두 비교하는 엄격한 동등 비교입니다.
</div> </details>

**Comment by yuiseo** [comment]
Q2. 다음 중 논리 연산자 &&의 결과가 true가 되는 경우는 무엇인가요?
(a) 피연산자 중 하나라도 true일 때
(b) 피연산자 모두 true일 때
(c) 피연산자 모두 false일 때
(d) 피연산자 중 하나가 false일 때
<details> <summary>퀴즈 정답</summary> <div markdown="1">
정답: (b) 피연산자 모두 true일 때. && 연산자는 모든 피연산자가 true일 때만 true를 반환합니다.
</div> </details>

**Comment by ilmerry** [comment]
<blockquote>
❓

퀴즈) 다음 코드의 출력 결과는?

```jsx
var x = "1";
console.log(typeof +x);
console.log(typeof (x + 2));
console.log(+"");
console.log(null + 1);
```

<details>
<summary>정답</summary>
number
string
0
1
</details>
    
</blockquote>
