### ISSUE TITLE
[8장] 제어문

### ISSUE THREAD

**Issue by yuiseo** [Pioneers-FE/DevBookshelf#11]
아래 템플릿을 복사해서 2개이상 퀴즈를 만들어주세요. 객관식, 주관식, 단답형 모두 상관없습니다!

```
Q. 퀴즈 내용
1.  1번
2.  2번
3.  3번

<details>
<summary>퀴즈 정답</summary>
<div markdown="1">    
정답 설명
</div>
</details>
```

**Comment by yuiseo** [comment]
Q1. 다음 코드의 출력 결과는 무엇인가요?
```jsx
for (let i = 1; i <= 5; i++) {
  if (i % 2 === 0) continue;
  console.log(i);
}
```
<details> <summary>퀴즈 정답</summary> <div markdown="1">
정답: 1, 3, 5. continue문에 의해 짝수일 때는 출력하지 않고 건너뛰기 때문에, 홀수인 1, 3, 5만 출력됩니다.
</div> </details>

**Comment by yuiseo** [comment]
Q2. 다음 코드에서 break문을 제거하면 출력 결과는 어떻게 되나요?
```javascript
const day = 'Tuesday';

switch (day) {
  case 'Monday':
    console.log('Start of the work week');
  case 'Tuesday':
    console.log('Second day of the work week');
  case 'Wednesday':
    console.log('Midweek');
    break;
  default:
    console.log('Not a work day');
}
```
<details> <summary>퀴즈 정답</summary> <div markdown="1">
정답: Second day of the work week, Midweek, Not a work day.

break문이 없기 때문에 day가 'Tuesday'인 경우부터 모든 case가 실행됩니다. 즉, console.log('Second day of the work week'), console.log('Midweek'), 그리고 default의 console.log('Not a work day')가 순서대로 출력됩니다.
</div> </details>

**Comment by ilmerry** [comment]
<blockquote>
❓ 다음 코드와 동일하게 동작하는 코드를 만들어보자

```jsx
var string = 'Hello world';
var search = 'l';
var count = 0;

for(var i = 0; i < string.length; i++ {
	if(string[i] !== search) continue;
	count++;
}

console.log(count);
```

<details>
<summary>정답</summary>
  console.log(string.match(new RegExp(search, ‘g’)).length)
</details>
</blockquote>
