### ISSUE TITLE
[9장] 타입 변환과 단축 평가

### ISSUE THREAD

**Issue by ilmerry** [Pioneers-FE/DevBookshelf#16]
아래 템플릿을 복사해서 2개이상 퀴즈를 만들어주세요. 객관식, 주관식, 단답형 모두 상관없습니다!

```
Q. 퀴즈 내용
1.  1번
2.  2번
3.  3번

<details>
<summary>퀴즈 정답</summary>
<div markdown="1">    
정답 설명
</div>
</details>
```

**Comment by hookim** [comment]
Q2. 다음 결과를 예측하시오.
```js
'' && 'Dog'
```

<details>
<summary>퀴즈 정답</summary>
<div markdown="1">    

`''`

</div>
</details>

**Comment by yuiseo** [comment]
### 퀴즈 1
**`+` 단항 연산자**는 피연산자를 숫자 타입으로 변환합니다. 다음 코드의 결과값은 무엇일까요?

```javascript
console.log(+'false');
console.log(+[10, 20]);
```

1. `NaN`, `30`  
2. `NaN`, `NaN`  
3. `NaN`, `10`  
4. `0`, `NaN`

<details>
<summary>퀴즈 정답</summary>
<div markdown="1">    
**정답: 2번**

- `+'false'`: `false`라는 문자열은 숫자로 변환할 수 없기 때문에 `NaN`이 됩니다.
- `+[10, 20]`: 배열은 기본적으로 문자열로 변환되고, 이를 다시 숫자로 변환하려고 하면 실패하여 `NaN`이 됩니다.
</div>
</details>

**Comment by yuiseo** [comment]
다음 코드에서 `foo`의 값은 무엇일까요?

```javascript
var foo = null ?? 'Hello';
var bar = '' || 'World';
console.log(foo, bar);
```

1. `'null'`, `'World'`  
2. `'Hello'`, `'World'`  
3. `null`, `'World'`  
4. `'Hello'`, `''`  

<details>
<summary>퀴즈 정답</summary>
<div markdown="1">    
**정답: 2번**
- `null ?? 'Hello'`: `null`은 `??` 연산자에 의해 `Hello`로 대체됩니다.
- `'' || 'World'`: 빈 문자열(`''`)은 Falsy 값이므로, `||` 연산자에 의해 `World`가 반환됩니다.
</div>
</details>
