### ISSUE TITLE
[10장] 객체 리터럴

### ISSUE THREAD

**Issue by ilmerry** [Pioneers-FE/DevBookshelf#17]
아래 템플릿을 복사해서 2개이상 퀴즈를 만들어주세요. 객관식, 주관식, 단답형 모두 상관없습니다!

```
Q. 퀴즈 내용
1.  1번
2.  2번
3.  3번

<details>
<summary>퀴즈 정답</summary>
<div markdown="1">    
정답 설명
</div>
</details>
```

**Comment by yuiseo** [comment]
다음 코드의 실행 결과는 무엇일까요?
```javascript

var person = {
  name: 'iseo',
  age: 25
};

// 프로퍼티 동적 생성
person.job = 'developer';

// 프로퍼티 삭제
delete person.age;

console.log(person);
```

1. { name: 'iseo', age: 25, job: 'developer' }
2. { name: 'iseo', job: 'developer' }
3. { name: 'iseo', job: 'developer', age: undefined }
4. { name: 'iseo' }


<details> <summary>퀴즈 정답</summary> <div markdown="1"> **정답: 2번**
person.job = 'developer': job 프로퍼티가 동적으로 추가됩니다.
delete person.age: age 프로퍼티가 삭제됩니다.
따라서, 최종적으로 person 객체는 { name: 'iseo', job: 'developer' }가 됩니다.
</div> </details>
