### ISSUE TITLE
[4장] 변수

### ISSUE THREAD

**Issue by yuiseo** [Pioneers-FE/DevBookshelf#2]
아래 템플릿을 복사해서 2개이상 퀴즈를 만들어주세요. 객관식, 주관식, 단답형 모두 상관없습니다!

```
Q. 퀴즈 내용
1.  1번
2.  2번
3.  3번

<details>
<summary>퀴즈 정답</summary>
<div markdown="1">    
정답 설명
</div>
</details>
```

**Comment by yuiseo** [comment]
### Q1. 자바스크립트에서 변수 선언과 할당이 순서대로 이루어지지 않은 코드입니다. 다음 코드가 실행될 때 콘솔에 출력되는 값은 무엇일까요?

```javascript
console.log(price); // ??
var price = 100;
console.log(price); // ??
```
<details> <summary>퀴즈 정답</summary> <div markdown="1"> - 첫 번째 `console.log(price);`는 `undefined`가 출력됩니다. 이유는 **변수 호이스팅**에 의해 `price` 변수가 선언된 상태지만, 아직 값이 할당되지 않았기 때문입니다. - 두 번째 `console.log(price);`는 `100`이 출력됩니다. `var price = 100;`에서 `price` 변수에 100이 할당되었기 때문입니다. </div> </details>

### Q2. 다음 코드에서 console.log(total);이 실행될 때 출력되는 값은 무엇이며, 그 이유는 무엇일까요?

```javascript
total = 50;
console.log(total); // ??
let total;
```
<details> <summary>퀴즈 정답</summary> <div markdown="1"> - `ReferenceError`가 발생합니다. `let` 키워드를 사용하여 변수를 선언할 때, **호이스팅은 되지만 TDZ(Temporal Dead Zone)**에 의해 선언 전 접근이 금지됩니다. 따라서, `let total;` 선언 전에 `total = 50;`으로 값을 할당하려는 시도에서 `ReferenceError`가 발생합니다. </div> </details>

**Comment by hookim** [comment]
### Q1. 아래 코드를 런타임과 연관지어 3단계로 나눠서 설명하세요.

```javascript
var x = 10;
```
<details>
<summary>퀴즈 정답</summary>
<div markdown="1">    
런타임 직전

1. x 변수 선언
2. undefined 초기화

런타임 

3. x 변수에 10 할당 
</div>
</details>
