### ISSUE TITLE
[6장] 데이터 타입

### ISSUE THREAD

**Issue by yuiseo** [Pioneers-FE/DevBookshelf#9]
아래 템플릿을 복사해서 2개이상 퀴즈를 만들어주세요. 객관식, 주관식, 단답형 모두 상관없습니다!

```
Q. 퀴즈 내용
1.  1번
2.  2번
3.  3번

<details>
<summary>퀴즈 정답</summary>
<div markdown="1">    
정답 설명
</div>
</details>
```

**Comment by yuiseo** [comment]
webhook test

**Comment by yuiseo** [comment]
Q1. 원시 타입과 객체 타입의 차이점은 무엇인가요?
<details> <summary>퀴즈 정답</summary> <div markdown="1">
정답: 원시 타입은 불변성이 있으며 값 자체를 저장하고, 객체 타입은 참조로 저장되며 변경 가능합니다.
</div> </details>

**Comment by yuiseo** [comment]
Q2. 자바스크립트에서 typeof null의 결과는 무엇인가요? 왜 그렇게 되는지 설명하세요.
<details> <summary>퀴즈 정답</summary> <div markdown="1">
정답: typeof null의 결과는 "object"입니다. 이는 자바스크립트의 초기 설계 오류로 인해 null이 빈 객체를 나타내는 포인터로 간주되어 object가 반환됩니다.
</div> </details>

**Comment by yuiseo** [comment]
Q3. 다음 중 원시 타입이 아닌 것은 무엇인가요?
(a) number
(b) string
(c) symbol
(d) array
<details> <summary>퀴즈 정답</summary> <div markdown="1">
정답: (d) array. 배열은 객체 타입으로 분류되며, 원시 타입이 아닙니다.
</div> </details>

**Comment by ilmerry** [comment]
<blockquote>
❓

퀴즈) 다음 코드의 출력값은?

```jsx
console.log(10 / 0 === Infinity);
console.log(1 * "String" === NAN);
console.log(1 * "String" === NaN);
```

<details>
<summary>정답</summary>
    
true

NAN is undefined 오류 출력

false. JS에서 어떤 값이 NaN인 경우는 서로 같지 않다고 판단한다. (https://developer.mozilla.org/ko/docs/Web/JavaScript/Equality_comparisons_and_sameness 참고)

</details>
    
</blockquote>

**Comment by ilmerry** [comment]
<blockquote>
❓
    
다음 식의 출력 결과는?

```jsx
console.log("String" + 1);
var hello;
console.log(`Hello ${hello}`);
```

<details>
<summary>정답</summary>
  String1
        
Hello undefined
</details>

</blockquote>

**Comment by hookim** [comment]
Q. 각각이 콘솔창에 출력되는 형태는? 

```js
const normalString = '안녕\
하세요'

const templateString = `안녕
하세요`
```

<details>
<summary>퀴즈 정답</summary>
<div markdown="1">   
 
```
"안녕하세요"

"안녕
하세요"
```
</div>
</details>
